schema_version = 1
client_version = "8.5.5"
architecture = "x86_64"
artifact_url = "https://download.foldingathome.org/releases/public/fah-client/debian-10-64bit/release/fah-client_8.5.5_amd64.deb"
artifact_size = 3180500
sha256 = "4f9c8bed9b2893752afb87e2796512ca0ca300ffc3d6035c518d56360370886c"
artifact_format = "deb"
minimum_foldingos_version = "0.1.0"
terms_url = "https://foldingathome.org/faq/opensource/"
executable_path = "/data/apps/fah/current/usr/bin/fah-client"
arguments = [
  "--config=/run/foldingos/fah/config.xml",
  "--log=/data/fah/log.txt",
  "--log-rotate-dir=/data/fah/log/",
]
