schema_version = 1
manifest_release = "0.1.0-1"
architecture = "x86_64"
artifact_format = "deb"
minimum_foldingos_version = "0.1.0"

[[packages]]
name = "foldops-agent"
version = "0.1.0-1"
roles = ["agent", "supervisor"]
artifact_url = "https://deb.folding-os.com/pool/main/f/foldops-agent/foldops-agent_0.1.0-1_amd64.deb"
artifact_size = 3127044
sha256 = "9022c393630e11d5cec5794ac77281671c7b0d634d630c92d95ad6de22d2151a"
verification_path = "/data/apps/foldops/current/foldops-agent/usr/bin/foldops-agent"

[[packages]]
name = "foldops-supervisor"
version = "0.1.0-1"
roles = ["supervisor"]
artifact_url = "https://deb.folding-os.com/pool/main/f/foldops-supervisor/foldops-supervisor_0.1.0-1_amd64.deb"
artifact_size = 3111920
sha256 = "a8b91ec03803259ade0bc3595218d74408390f6ac4e0f077cc47ba85edaaa8d5"
verification_path = "/data/apps/foldops/current/foldops-supervisor/usr/bin/foldops-supervisor"

[[packages]]
name = "foldops-web"
version = "0.1.0"
roles = ["supervisor"]
artifact_url = "https://deb.folding-os.com/pool/main/f/foldops-web/foldops-web_0.1.0_all.deb"
artifact_size = 174466
sha256 = "e560956f0aa6f77677af9bbac464a71ebcf0ff1da19877070f6f8dc05f738ecf"
verification_path = "/data/apps/foldops/current/foldops-web/usr/share/foldops/web/index.html"
