schema_version = 2
manifest_release = "0.1.0-5"
architecture = "x86_64"
artifact_format = "layout-tar-zst"
minimum_foldingos_version = "0.1.0"

[[packages]]
name = "foldops-agent"
version = "0.1.0"
roles = ["agent", "supervisor"]
install_prefix = "foldops-agent"
artifact_url = "https://packages.folding-os.com/foldops/0.1.0-5/foldops-agent-x86_64.tar.zst"
artifact_size = 3793639
sha256 = "9d92741314f128fcf1c5dcd35aed0c09dd853a4dddb8d0006b0c2f4cd77a89f6"
verification_path = "/data/apps/foldops/current/foldops-agent/usr/bin/foldops-agent"

[[packages]]
name = "foldops-supervisor"
version = "0.1.0"
roles = ["supervisor"]
install_prefix = "foldops-supervisor"
artifact_url = "https://packages.folding-os.com/foldops/0.1.0-5/foldops-supervisor-x86_64.tar.zst"
artifact_size = 3898551
sha256 = "6e518334773f047dfceb83cc1eceb6e744d6ce2d76529c197220e754b156ca0c"
verification_path = "/data/apps/foldops/current/foldops-supervisor/usr/bin/foldops-supervisor"

[[packages]]
name = "foldops-web"
version = "0.1.0"
roles = ["supervisor"]
install_prefix = "foldops-web"
artifact_url = "https://packages.folding-os.com/foldops/0.1.0-5/foldops-web-x86_64.tar.zst"
artifact_size = 177531
sha256 = "58a32b152130fb9efbbc862ba4441662044ae5c89be8ba73ffd3a21292d12c20"
verification_path = "/data/apps/foldops/current/foldops-web/usr/share/foldops/web/index.html"
