use std::fs;
use std::net::Ipv4Addr;
use std::process::{Command, Stdio};

use crate::fs_atomic::atomic_write;
use crate::identity::candidate_network_interfaces;
use crate::paths::AppliancePaths;
use crate::provision::serve::render_ipxe_bootstrap_script;
use crate::provision::util::{
    command_output, copy_regular_file, empty_human_result, ensure_enrollment_token,
    read_provision_listen_host,
};
use crate::role::require_supervisor_role;

const IPXE_BOOTSTRAP_FILENAME: &str = "ipxe.efi";
const IPXE_AUTOEXEC_FILENAME: &str = "autoexec.ipxe";

struct ProvisionBootEnvironment {
    iface: String,
    host: String,
    subnet: String,
    boot_base: String,
    boot_url: String,
}

pub fn provision_boot(paths: &AppliancePaths) -> Result<serde_json::Value, String> {
    require_supervisor_role(paths)?;
    let _ = ensure_enrollment_token(paths)?;
    let env = resolve_provision_boot_environment(paths)?;
    prepare_provision_boot_assets(paths, &env)?;
    let config = render_dnsmasq_config_from_environment(paths, &env);
    atomic_write(&paths.provision_boot_dnsmasq_config, config.as_bytes(), 0o644)?;
    println!(
        "FoldingOS network boot assistance using {}",
        paths.provision_boot_dnsmasq_config.display()
    );
    start_dnsmasq_process(&paths.provision_boot_dnsmasq_config)?;
    Ok(empty_human_result())
}

fn resolve_provision_boot_environment(paths: &AppliancePaths) -> Result<ProvisionBootEnvironment, String> {
    let iface = read_provision_boot_interface(paths)?;
    let host = resolve_provision_boot_host(&iface)?;
    let listen_host = read_provision_listen_host(paths)?;
    let port = listen_host
        .split(':')
        .nth(1)
        .unwrap_or("8743")
        .to_string();
    let subnet = interface_ipv4_subnet(&iface)?;
    let boot_base = if listen_host.contains(':') {
        format!("http://{host}:{port}")
    } else {
        format!("http://{host}")
    };
    let boot_url = format!("{boot_base}/boot/ipxe/bootstrap.ipxe");
    Ok(ProvisionBootEnvironment {
        iface,
        host,
        subnet,
        boot_base,
        boot_url,
    })
}

fn prepare_provision_boot_assets(paths: &AppliancePaths, env: &ProvisionBootEnvironment) -> Result<(), String> {
    fs::create_dir_all(&paths.provision_boot_tftp_root).map_err(|error| error.to_string())?;
    let source = paths
        .provision_boot_assets_dir
        .join("ipxe")
        .join(IPXE_BOOTSTRAP_FILENAME);
    let destination = paths.provision_boot_tftp_root.join(IPXE_BOOTSTRAP_FILENAME);
    copy_regular_file(&source, &destination)
        .map_err(|error| format!("stage iPXE bootstrap loader: {error}"))?;
    let autoexec = render_ipxe_bootstrap_script(&env.boot_base);
    fs::write(
        paths.provision_boot_tftp_root.join(IPXE_AUTOEXEC_FILENAME),
        autoexec,
    )
    .map_err(|error| format!("stage iPXE autoexec script: {error}"))?;
    Ok(())
}

fn render_dnsmasq_config_from_environment(
    paths: &AppliancePaths,
    env: &ProvisionBootEnvironment,
) -> String {
    let tftp_boot = format!("{IPXE_BOOTSTRAP_FILENAME},{},{}", env.host, env.host);
    let lines = [
        "# Generated by foldingosctl provision boot".to_string(),
        "bind-dynamic".into(),
        format!("interface={}", env.iface),
        "except-interface=lo".into(),
        render_provision_dhcp_range_line(paths, &env.subnet),
        "enable-tftp".into(),
        format!("tftp-root={}", paths.provision_boot_tftp_root.display()),
        "dhcp-match=set:ipxe,175".into(),
        "dhcp-match=set:ipxe,option:user-class,iPXE".into(),
        "dhcp-match=set:efi,option:client-arch,7".into(),
        "dhcp-match=set:efi,option:client-arch,9".into(),
        format!(
            "dhcp-boot=tag:ipxe,{},,{}",
            env.boot_url, env.host
        ),
        format!("dhcp-boot=tag:efi,tag:!ipxe,{tftp_boot}"),
        format!("dhcp-boot=tag:!ipxe,{tftp_boot}"),
        format!(
            "dhcp-option=tag:efi,tag:!ipxe,option:bootfile-name,{IPXE_BOOTSTRAP_FILENAME}"
        ),
        format!("dhcp-option=66,{}", env.host),
        format!(
            "pxe-service=tag:!ipxe,X86-64_EFI,\"FoldingOS Network Install\",{IPXE_BOOTSTRAP_FILENAME},{}",
            env.host
        ),
        "log-dhcp".into(),
        "log-queries".into(),
    ];
    format!("{}\n", lines.join("\n"))
}

fn provision_boot_isolated_network_enabled(paths: &AppliancePaths) -> bool {
    paths.provision_boot_isolated_network.exists()
}

fn render_provision_dhcp_range_line(paths: &AppliancePaths, subnet: &str) -> String {
    if !provision_boot_isolated_network_enabled(paths) {
        return format!("dhcp-range={subnet},proxy,255.255.255.0");
    }
    let Ok(network) = subnet.parse::<Ipv4Addr>() else {
        return format!("dhcp-range={subnet},proxy,255.255.255.0");
    };
    let octets = network.octets();
    let start = Ipv4Addr::new(octets[0], octets[1], octets[2], octets[3].saturating_add(10));
    let end = Ipv4Addr::new(octets[0], octets[1], octets[2], octets[3].saturating_add(200));
    format!(
        "dhcp-range={start},{end},255.255.255.0,12h"
    )
}

fn read_provision_boot_interface(paths: &AppliancePaths) -> Result<String, String> {
    if let Ok(content) = fs::read_to_string(&paths.provision_boot_interface) {
        let iface = content.trim();
        if !iface.is_empty() {
            return Ok(iface.to_string());
        }
    }
    select_network_interface()
}

fn select_network_interface() -> Result<String, String> {
    let output = Command::new("networkctl")
        .args(["--no-legend", "--no-pager", "list"])
        .output()
        .map_err(|error| error.to_string())?;
    if !output.status.success() {
        return Err("list network interfaces failed".into());
    }
    let listing = String::from_utf8_lossy(&output.stdout);
    let interfaces = candidate_network_interfaces(&listing)?;
    interfaces
        .into_iter()
        .next()
        .ok_or_else(|| "no wired network interface found".into())
}

fn resolve_provision_boot_host(iface: &str) -> Result<String, String> {
    if let Ok(address) = routable_ipv4_address_for_interface(iface) {
        return Ok(address);
    }
    ipv4_address_from_interface(iface)
}

fn routable_ipv4_address_for_interface(iface: &str) -> Result<String, String> {
    if let Ok(status) = command_output("networkctl", &["--no-legend", "--no-pager", "status", iface])
    {
        if let Some(address) = parse_ipv4_address(&status) {
            return Ok(address);
        }
    }
    ipv4_address_from_interface(iface)
}

fn parse_ipv4_address(status: &str) -> Option<String> {
    for line in status.lines() {
        let trimmed = line.trim();
        if !trimmed.starts_with("Address:") {
            continue;
        }
        for token in trimmed.split_whitespace().skip(1) {
            if let Some(ip) = token.split('/').next() {
                if let Ok(parsed) = ip.parse::<Ipv4Addr>() {
                    if !parsed.is_loopback() && !parsed.is_unspecified() {
                        return Some(parsed.to_string());
                    }
                }
            }
        }
    }
    None
}

fn ipv4_address_from_interface(iface: &str) -> Result<String, String> {
    let output = command_output("ip", &["-4", "-o", "addr", "show", "dev", iface])?;
    for line in output.lines() {
        for token in line.split_whitespace() {
            if let Some(ip) = token.split('/').next() {
                if let Ok(parsed) = ip.parse::<Ipv4Addr>() {
                    if !parsed.is_loopback() && !parsed.is_unspecified() {
                        return Ok(parsed.to_string());
                    }
                }
            }
        }
    }
    Err(format!("no IPv4 subnet found on {iface}"))
}

fn interface_ipv4_subnet(iface: &str) -> Result<String, String> {
    let output = command_output("ip", &["-4", "-o", "addr", "show", "dev", iface])?;
    for line in output.lines() {
        let tokens: Vec<&str> = line.split_whitespace().collect();
        if tokens.len() < 4 {
            continue;
        }
        let address = tokens[3];
        let Some((ip, prefix)) = address.split_once('/') else {
            continue;
        };
        let Ok(ipv4) = ip.parse::<Ipv4Addr>() else {
            continue;
        };
        let Ok(prefix_len) = prefix.parse::<u8>() else {
            continue;
        };
        let mask = ipv4_mask(prefix_len);
        let network = Ipv4Addr::new(
            ipv4.octets()[0] & mask.octets()[0],
            ipv4.octets()[1] & mask.octets()[1],
            ipv4.octets()[2] & mask.octets()[2],
            ipv4.octets()[3] & mask.octets()[3],
        );
        return Ok(network.to_string());
    }
    Err(format!("no IPv4 subnet found on {iface}"))
}

fn ipv4_mask(prefix_len: u8) -> Ipv4Addr {
    if prefix_len == 0 {
        return Ipv4Addr::new(0, 0, 0, 0);
    }
    let mask = if prefix_len >= 32 {
        u32::MAX
    } else {
        u32::MAX << (32 - prefix_len)
    };
    Ipv4Addr::from(mask)
}

fn start_dnsmasq_process(config_path: &std::path::Path) -> Result<(), String> {
    let status = Command::new("dnsmasq")
        .args([
            "--keep-in-foreground",
            &format!("--conf-file={}", config_path.display()),
        ])
        .stdout(Stdio::inherit())
        .stderr(Stdio::inherit())
        .status()
        .map_err(|error| error.to_string())?;
    if status.success() {
        Ok(())
    } else {
        Err(format!("dnsmasq exited with status {status}"))
    }
}
