package main

import (
	"bufio"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

const (
	provisionBootTFTPRootDefault      = "/data/provision/boot/tftp"
	provisionBootAllowlistPathDefault = "/data/config/provision/boot-allowlist"
	provisionBootInstallDiskAllowlistPathDefault = "/data/config/provision/boot-install-disk-allowlist"
	provisionBootInterfacePathDefault = "/data/config/provision/boot.interface"
	provisionBootDnsmasqConfigDefault   = "/data/config/provision/dnsmasq.conf"
	provisionBootIsolatedNetworkPathDefault = "/data/config/provision/boot-isolated-network"
	provisionBootAssetsDirDefault     = "/usr/share/foldingos/boot"
	ipxeBootstrapFilename             = "ipxe.efi"
	ipxeAutoexecFilename              = "autoexec.ipxe"
)

var macAddressPattern = regexp.MustCompile(`^([0-9a-f]{2}:){5}[0-9a-f]{2}$`)

var (
	provisionBootTFTPRoot      = provisionBootTFTPRootDefault
	provisionBootAllowlistPath = provisionBootAllowlistPathDefault
	provisionBootInstallDiskAllowlistPath = provisionBootInstallDiskAllowlistPathDefault
	provisionBootInterfacePath = provisionBootInterfacePathDefault
	provisionBootDnsmasqConfig = provisionBootDnsmasqConfigDefault
	provisionBootIsolatedNetworkPath = provisionBootIsolatedNetworkPathDefault
	provisionBootAssetsDir       = provisionBootAssetsDirDefault
	startDnsmasqProcess        = startDnsmasqProcessDirect
	resolveProvisionBootHost   = resolveProvisionBootHostFromNetwork
	interfaceIPv4Subnet        = interfaceIPv4SubnetFromInterface
)

type provisionBootEnvironment struct {
	iface    string
	host     string
	port     string
	subnet   string
	bootBase string
	bootURL  string
}

func provisionBoot() error {
	if err := requireSupervisorRole(); err != nil {
		return err
	}
	if _, err := ensureEnrollmentToken(); err != nil {
		return err
	}
	env, err := resolveProvisionBootEnvironment()
	if err != nil {
		return err
	}
	if err := prepareProvisionBootAssets(env); err != nil {
		return err
	}
	config := renderDnsmasqConfigFromEnvironment(env)
	if err := atomicWrite(provisionBootDnsmasqConfig, []byte(config), 0644); err != nil {
		return err
	}
	fmt.Printf("FoldingOS network boot assistance using %s\n", provisionBootDnsmasqConfig)
	return startDnsmasqProcess(provisionBootDnsmasqConfig)
}

func resolveProvisionBootEnvironment() (provisionBootEnvironment, error) {
	iface, err := readProvisionBootInterface()
	if err != nil {
		return provisionBootEnvironment{}, err
	}
	host, err := resolveProvisionBootHost(iface)
	if err != nil {
		return provisionBootEnvironment{}, err
	}
	listenHost, err := readProvisionListenHost()
	if err != nil {
		return provisionBootEnvironment{}, err
	}
	_, port, err := net.SplitHostPort(listenHost)
	if err != nil {
		return provisionBootEnvironment{}, err
	}
	subnet, err := interfaceIPv4Subnet(iface)
	if err != nil {
		return provisionBootEnvironment{}, err
	}
	bootBase := "http://" + net.JoinHostPort(host, port)
	return provisionBootEnvironment{
		iface:    iface,
		host:     host,
		port:     port,
		subnet:   subnet,
		bootBase: bootBase,
		bootURL:  bootBase + "/boot/ipxe/bootstrap.ipxe",
	}, nil
}

func prepareProvisionBootAssets(env provisionBootEnvironment) error {
	if err := os.MkdirAll(provisionBootTFTPRoot, 0755); err != nil {
		return err
	}
	source := filepath.Join(provisionBootAssetsDir, "ipxe", ipxeBootstrapFilename)
	destination := filepath.Join(provisionBootTFTPRoot, ipxeBootstrapFilename)
	if err := copyRegularFile(source, destination); err != nil {
		return fmt.Errorf("stage iPXE bootstrap loader: %w", err)
	}
	autoexec := renderIPXEBootstrapScript(env.bootBase)
	if err := os.WriteFile(filepath.Join(provisionBootTFTPRoot, ipxeAutoexecFilename), []byte(autoexec), 0644); err != nil {
		return fmt.Errorf("stage iPXE autoexec script: %w", err)
	}
	return nil
}

func renderDnsmasqConfig() (string, error) {
	env, err := resolveProvisionBootEnvironment()
	if err != nil {
		return "", err
	}
	return renderDnsmasqConfigFromEnvironment(env), nil
}

func renderDnsmasqConfigFromEnvironment(env provisionBootEnvironment) string {
	tftpBoot := ipxeBootstrapFilename + "," + env.host + "," + env.host
	lines := []string{
		"# Generated by foldingosctl provision boot",
		"bind-dynamic",
		"interface=" + env.iface,
		"except-interface=lo",
		renderProvisionDhcpRangeLine(env.subnet),
		"enable-tftp",
		"tftp-root=" + provisionBootTFTPRoot,
		"dhcp-match=set:ipxe,175",
		"dhcp-match=set:ipxe,option:user-class,iPXE",
		"dhcp-match=set:efi,option:client-arch,7",
		"dhcp-match=set:efi,option:client-arch,9",
		"dhcp-boot=tag:ipxe," + env.bootURL + ",," + env.host,
		"dhcp-boot=tag:efi,tag:!ipxe," + tftpBoot,
		"dhcp-boot=tag:!ipxe," + tftpBoot,
		"dhcp-option=tag:efi,tag:!ipxe,option:bootfile-name," + ipxeBootstrapFilename,
		"dhcp-option=66," + env.host,
		"pxe-service=tag:!ipxe,X86-64_EFI,\"FoldingOS Network Install\"," + ipxeBootstrapFilename + "," + env.host,
		"log-dhcp",
		"log-queries",
	}
	return strings.Join(lines, "\n") + "\n"
}

func provisionBootIsolatedNetworkEnabled() bool {
	_, err := os.Stat(provisionBootIsolatedNetworkPath)
	return err == nil
}

func renderProvisionDhcpRangeLine(subnet string) string {
	if !provisionBootIsolatedNetworkEnabled() {
		return "dhcp-range=" + subnet + ",proxy,255.255.255.0"
	}
	network := net.ParseIP(subnet).To4()
	if network == nil {
		return "dhcp-range=" + subnet + ",proxy,255.255.255.0"
	}
	start := net.IP(append(net.IP(nil), network...))
	end := net.IP(append(net.IP(nil), network...))
	start[3] += 10
	end[3] += 200
	return fmt.Sprintf(
		"dhcp-range=%s,%s,255.255.255.0,12h",
		start.String(),
		end.String(),
	)
}

func readProvisionBootInterface() (string, error) {
	content, err := os.ReadFile(provisionBootInterfacePath)
	if err == nil {
		iface := strings.TrimSpace(string(content))
		if iface != "" {
			return iface, nil
		}
	} else if !os.IsNotExist(err) {
		return "", err
	}
	return selectNetworkInterface()
}

func resolveProvisionBootHostFromNetwork(iface string) (string, error) {
	address, err := routableIPv4AddressForInterface(iface)
	if err != nil {
		return "", err
	}
	host, _, err := net.SplitHostPort(net.JoinHostPort(address, "0"))
	if err != nil {
		return "", err
	}
	return host, nil
}

func routableIPv4AddressForInterface(iface string) (string, error) {
	status, err := output("networkctl", "--no-legend", "--no-pager", "status", iface)
	if err == nil {
		if address, err := parseIPv4Address(status); err == nil && address != "" {
			return address, nil
		}
	}
	return ipv4AddressFromInterface(iface)
}

func interfaceIPv4SubnetFromInterface(iface string) (string, error) {
	resolved, err := resolveNetworkInterfaceName(iface)
	if err != nil {
		return "", err
	}
	ifaceObj, err := net.InterfaceByName(resolved)
	if err != nil {
		return "", err
	}
	addrs, err := ifaceObj.Addrs()
	if err != nil {
		return "", err
	}
	for _, addr := range addrs {
		ipNet, ok := addr.(*net.IPNet)
		if !ok || ipNet.IP.To4() == nil {
			continue
		}
		mask := ipNet.Mask
		network := ipNet.IP.Mask(mask)
		return network.String(), nil
	}
	return "", fmt.Errorf("no IPv4 subnet found on %s", resolved)
}

func isBootClientEligible(mac, enrollmentToken string) error {
	mac = normalizeMAC(mac)
	if mac == "" {
		return errors.New("client MAC address is required")
	}
	if enrollmentToken != "" {
		if err := validateEnrollmentToken(enrollmentToken); err != nil {
			return err
		}
		return nil
	}
	allowed, err := loadBootAllowlist()
	if err != nil {
		return err
	}
	if containsString(allowed, mac) {
		return nil
	}
	return errors.New("client is not enrolled for network boot")
}

func loadBootAllowlist() ([]string, error) {
	allowed, err := readBootAllowlistEntries()
	if err != nil {
		return nil, err
	}
	if len(allowed) == 0 {
		return nil, errors.New("client is not enrolled for network boot")
	}
	return allowed, nil
}

func readBootAllowlistEntries() ([]string, error) {
	content, err := os.ReadFile(provisionBootAllowlistPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	var allowed []string
	scanner := bufio.NewScanner(strings.NewReader(string(content)))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		mac, err := parseMACAddress(line)
		if err != nil {
			continue
		}
		allowed = append(allowed, mac)
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	return allowed, nil
}

func saveBootAllowlist(allowed []string) error {
	var lines []string
	for _, mac := range allowed {
		lines = append(lines, mac)
	}
	content := strings.Join(lines, "\n")
	if len(lines) > 0 {
		content += "\n"
	}
	return atomicWrite(provisionBootAllowlistPath, []byte(content), 0644)
}

func provisionAllowBoot(mac, installDisk string) error {
	if err := requireSupervisorRole(); err != nil {
		return err
	}
	mac, err := parseMACAddress(mac)
	if err != nil {
		return err
	}
	if installDisk != "" {
		installDisk, err = parseProvisionInstallDiskPath(installDisk)
		if err != nil {
			return err
		}
	}
	allowed, err := readBootAllowlistEntries()
	if err != nil {
		return err
	}
	if containsString(allowed, mac) {
		if installDisk != "" {
			if err := saveBootInstallDiskMapping(mac, installDisk); err != nil {
				return err
			}
			fmt.Printf("Pinned network install target disk %s for MAC %s.\n", installDisk, mac)
			return nil
		}
		fmt.Printf("MAC %s is already allowed for network boot.\n", mac)
		return nil
	}
	allowed = append(allowed, mac)
	if err := saveBootAllowlist(allowed); err != nil {
		return err
	}
	if installDisk != "" {
		if err := saveBootInstallDiskMapping(mac, installDisk); err != nil {
			return err
		}
	}
	fmt.Printf("Allowed MAC %s for network boot.\n", mac)
	if installDisk != "" {
		fmt.Printf("Pinned network install target disk %s for MAC %s.\n", installDisk, mac)
	}
	return nil
}

func provisionAllowBootCommand(args []string) error {
	var installDisk string
	remaining := args
	for len(remaining) > 0 {
		switch remaining[0] {
		case "--disk":
			if len(remaining) < 2 {
				return errors.New("--disk requires a whole-disk device path")
			}
			installDisk = remaining[1]
			remaining = remaining[2:]
		default:
			if len(remaining) != 1 {
				return fmt.Errorf("unexpected allow-boot argument %q", remaining[0])
			}
			return provisionAllowBoot(remaining[0], installDisk)
		}
	}
	return errors.New("allow-boot requires a MAC address")
}

func readBootInstallDiskAllowlistEntries() (map[string]string, error) {
	content, err := os.ReadFile(provisionBootInstallDiskAllowlistPath)
	if err != nil {
		if os.IsNotExist(err) {
			return map[string]string{}, nil
		}
		return nil, err
	}
	mappings := map[string]string{}
	scanner := bufio.NewScanner(strings.NewReader(string(content)))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) != 2 {
			continue
		}
		mac, err := parseMACAddress(fields[0])
		if err != nil {
			continue
		}
		disk, err := parseProvisionInstallDiskPath(fields[1])
		if err != nil {
			continue
		}
		mappings[mac] = disk
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	return mappings, nil
}

func saveBootInstallDiskMapping(mac, installDisk string) error {
	mappings, err := readBootInstallDiskAllowlistEntries()
	if err != nil {
		return err
	}
	mappings[mac] = installDisk
	var lines []string
	for _, allowedMAC := range sortedMapKeys(mappings) {
		lines = append(lines, allowedMAC+" "+mappings[allowedMAC])
	}
	content := strings.Join(lines, "\n")
	if len(lines) > 0 {
		content += "\n"
	}
	return atomicWrite(provisionBootInstallDiskAllowlistPath, []byte(content), 0644)
}

func bootInstallDiskForMAC(mac string) string {
	mac = normalizeMAC(mac)
	if mac == "" {
		return ""
	}
	mappings, err := readBootInstallDiskAllowlistEntries()
	if err != nil {
		return ""
	}
	return mappings[mac]
}

func sortedMapKeys(mappings map[string]string) []string {
	keys := make([]string, 0, len(mappings))
	for key := range mappings {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func parseMACAddress(value string) (string, error) {
	mac := normalizeMAC(value)
	if !macAddressPattern.MatchString(mac) {
		return "", fmt.Errorf("invalid MAC address %q", value)
	}
	return mac, nil
}

func normalizeMAC(value string) string {
	value = strings.TrimSpace(strings.ToLower(value))
	value = strings.ReplaceAll(value, "-", ":")
	return value
}

func renderIPXEBootstrapScript(host string) string {
	base := strings.TrimRight(host, "/")
	scriptURL := base + "/boot/ipxe/script.ipxe?mac=${net0/mac}&arch=${buildarch}"
	return strings.Join([]string{
		"#!ipxe",
		"dhcp",
		"set foldingos-server " + base,
		"chain " + scriptURL,
	}, "\n") + "\n"
}

func renderIPXEInstallScript(host, mac, enrollmentToken, installDisk string) (string, error) {
	if err := isBootClientEligible(mac, enrollmentToken); err != nil {
		return "", err
	}
	token, err := readEnrollmentToken()
	if err != nil {
		return "", err
	}
	if enrollmentToken != "" {
		token = enrollmentToken
	}
	installDisk = strings.TrimSpace(installDisk)
	if installDisk == "" {
		installDisk = bootInstallDiskForMAC(mac)
	}
	if installDisk != "" {
		installDisk, err = parseProvisionInstallDiskPath(installDisk)
		if err != nil {
			return "", err
		}
	}
	base := strings.TrimRight(host, "/")
	kernelURL := base + "/boot/vmlinuz"
	initrdURL := base + "/boot/install-initramfs.cpio.gz"
	cmdlineParts := []string{
		"foldingos.install=1",
		"foldingos.supervisor=" + base,
		"foldingos.enrollment-token=" + token,
		"ip=dhcp",
		"console=ttyS0,115200",
		"console=tty1",
	}
	if installDisk != "" {
		cmdlineParts = append(cmdlineParts, "foldingos.install-disk="+installDisk)
	}
	cmdline := strings.Join(cmdlineParts, " ")
	return strings.Join([]string{
		"#!ipxe",
		"kernel " + kernelURL + " " + cmdline,
		"initrd " + initrdURL,
		"boot",
	}, "\n") + "\n", nil
}

func provisionBootHTTPBase(request *http.Request) (string, error) {
	host := strings.TrimSpace(request.Header.Get("X-FoldingOS-Boot-Host"))
	if host != "" {
		return host, nil
	}
	if request.Host != "" {
		scheme := "http"
		return scheme + "://" + request.Host, nil
	}
	return "", errors.New("boot host is unavailable")
}

func copyRegularFile(source, destination string) error {
	in, err := os.Open(source)
	if err != nil {
		return err
	}
	defer in.Close()
	out, err := os.OpenFile(destination, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0644)
	if err != nil {
		return err
	}
	defer out.Close()
	if _, err := io.Copy(out, in); err != nil {
		return err
	}
	return out.Sync()
}

func startDnsmasqProcessDirect(configPath string) error {
	cmd := execCommand("dnsmasq", "--keep-in-foreground", "--conf-file="+configPath)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}
